config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  resources :messages
  resources :chats
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'chats#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  put 'chatupdate', to: 'chats#update', as: 'chatupdate'
  put 'userupdate', to: 'users#update', as: 'userupdate'
  put 'messageupdate', to: 'messages#update', as: 'messageupdate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    # Класс, описывающий таблицу с чатами в базе данных
    has_many :messages
    has_many :users, through: :messages
    serialize :userlist, Array
    validates :name, length: {minimum: 1, maximum: 100}, presence: true, allow_blank: false
end

app/models/message.rb
class Message < ApplicationRecord
  # Класс, описывающий таблицу с сообщениями в базе данных
  belongs_to :user
  belongs_to :chat
  mount_uploader :file, FileUploader
  validates :user_id, presence: true, allow_blank: false
  validates :chat_id, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
    # Класс, описывающий таблицу с пользователями в базе данных
    has_many :messages
    has_secure_password
    validates :login, length:{minimum:1, maximum:100}, presence: true, uniqueness: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    # метод, идентифицирующий вошедшего в систему пользователя
    def current_user
      return @current_user if @current_user.present?

      if session[:user_id].present?
        @current_user = User.find_by(id: session[:user_id])
      else
        @current_user = nil
      end

      cookies[:user_id] = session[:user_id]

      @current_user
    end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @chats = Chat.all
    render 'index'
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
    @chats = Chat.all
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)
    @chat.userlist.push(current_user.id)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    # добавление id пользователя в массив пользователей, кому доступен данный чат
    @room = Chat.find_by_id(@chat.id)
      if (params[:useradd].to_i != 0) then
        @room.userlist.push(params[:useradd].to_i)
      end
      @room.save
    respond_to do |format| 
      format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
      format.json { render :show, status: :ok, location: @chat }
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    # удаляет пользователя из массива пользователей, имеющих доступ к чату.
    @chat.userlist.delete(current_user.id)
    if @chat.userlist.size() ==  0 then
      #@chat.destroy
    end
    @chat.save 
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:name, :useradd, {userlist: []})
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save
    SendMessageJob.perform_later(@message)
    redirect_to @message.chat
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :chat_id, :file)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Если пользователь вводит правильные логин и пароль, то система его авторизует и запоминает егo id
    user = User.find_by_login(params[:login])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Username or password is invalid"
      render "new"
    end
  end

  def destroy
    # Когда пользователь выходит из системы, информация о нем обнуляется
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_form.html.erb
<!-- Форма для создания нового чата -->
<%= form_with(model: chat, local: true) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group mb-3">
    <%= form.label "Создать новый чат" %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Название" %>
  </div>

  <div class="actions">
    <%= form.submit "Создать", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<!-- Форма для добавления пользователя в чат -->
<%= form_with(model: @chat, local: true) do |form| %>
    <div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <div class="card-body">
            <h3 class="card-title mb-3">Добавление пользователя в чат</h3>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= form.label "Выберите пользователя из списка: " %>
                        <div class="input-group"> 
                          <!-- Выбираем из базы данных пользователей, еще не находящихся в чате и заносим их в select_tag-->
                          <% @allstructs = User.all.map {|usr| [usr.login, usr.id]} %>
                          <% @userid_array = [] %>
                          <% @allstructs.each { |struct| if @chat.userlist.exclude?(struct[1]) then @userid_array.push(struct) end } %>
                          <%= select_tag "useradd", options_for_select(@userid_array), class: "select" %> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="actions">
                <div class="col-sm-14">
                <!-- Добавляем выбранного с помощью select_tag пользователя в чат-->
                <p><%= form.submit "Добавить", class: "btn btn-primary btn-block confirm-button" %></p>
                </div>
            </div>
            <div class="col-sm-14">
              <p><%= link_to 'Вернуться назад', chats_path, class: 'btn btn-primary btn-block linkcolor'%></p>
            </div>
        </div>
    </div>
    </div>
<% end %>

app/views/chats/index.html.erb
<!-- Проверка авторизован ли пользователь -->
<% if current_user %> 
  <div id="chat-id" data-chat-id="<%= @chat.try(:id) %>"></div>
  <div id="user-id" data-user-id="<%= current_user.id %>"></div>

  <div class="container-fluid chatbody">
    <div class="row">
      <div class="col-3 chats-sidebar">
        <div class="card no-outline">
          <div class="card-body chatbody">
            <!-- Информация о текущем имени пользователя -->
            <small>Ваш никнейм:</small><br>
            <b><%= current_user.login %> <br></b>
            <%= link_to 'Выйти', logout_path, method: :delete %>
          </div>
        </div>
        <hr>
        <div class="chats-list">
          <!-- Отображение формы для создания нового чата -->
          <%= render 'form', chat: Chat.new %>
        </div>
        <hr>
        <div id="chats">
          <% @chats.each do |chat| %>
            <!-- Проверяет для каждого чата, есть ли у пользователя доступ к нему. Если есть, то отображает его -->
            <% if chat.userlist.include?(current_user.id) %>
              <%= link_to chat, class: "room-link" do %>
                <% active_class = (@chat == chat) ? 'active' : '' %>
                <div class="card no-outline mb-3 room-card <%= active_class %>">
                  <div class="card-body namechat">
                    <!--Информация о названии чата и текущем количестве участников в нем -->
                    <span class="name"><b><%= chat.name %></b></span><br>
                    <span class="member-count"><small><%= chat.userlist.uniq.count %> участник(-ов)</small></span>
                  </div>
                  <div class="card-body deletecol">
                    <table>
                    <!-- Предоставление возможности покинуть чат -->
                    <td><%= link_to '✖', chat, method: :delete, data: { confirm: 'Вы действительно хотите покинуть чат?' } %></td>
                    </table>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="col-9">
        <% if @chat.present? %>
          <div class="chat-room">
            <nav class="navbar navbar-light">
              <span class="navbar-brand" href="#">
                <b><%= @chat.name %></b>
              </span>
              <!-- Выбирает из базы данных пользователей, имеющих доступ к данном чату и записывает их в select_tag -->
              <% @allusers = User.all.map {|usr| [usr.login, usr.id]} %>
              <% @users_array = [] %>
              <% @allusers.each { |usr| if @chat.userlist.include?(usr[1]) then @users_array.push(usr) end } %>
              <%= select_tag "users", options_for_select(@users_array), prompt: "Список участников (развернуть)",  class: "select selectwidth" %> 
              <!-- Ссылка на страницу с добавлением новых пользователей в чат-->
              <small><%= link_to '+', edit_chat_path(@chat), class: "adduser" %></small>
            </nav>
            <div class = "chat-box">
              <!-- Отображение формы для создания нового сообщения-->
              <%= render 'messages/form', message: Message.new, chat: @chat %>
            </div>
            <div id="messages">
              <!-- С помощью цикла отображаются все сообщения в выбранном чате -->
              <% @chat.messages.each do |message| %>
                <%= render 'messages/message', message: message %> 
              <% end %>
            </div>   
          </div>
        <% end %>
      </div>
    </div> 
  </div>

<% else %>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Мессенджер</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark"><%= link_to 'Зарегистрироваться', signup_path, class: "sign-in-link" %></span>
      <span class="p-2 text-dark"><%= link_to 'Войти', login_path %></span>
    </nav>
  </div>
  <div class='container'>
    <div class='hero-unit'>            
      <h1>Добро пожаловать!</h1>
      <p>Для использования месенджера Вам необходимо авторизоваться.</p>
    </div>
  </div>
<% end %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Userlist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.name %></td>
        <td><%= chat.userlist %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<!-- Форма для создания новых сообщений-->
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :chat_id, value: chat.id %>

  <div class="input-group">
    <%= form.text_field :content, placeholder: "Сообщение", class: 'form-control mr-2' %>
    <div>
      <label class="btn btn-default btn-change-avatar">
      Прикрепить файл
        <span style="display:none;">
          <%= form.file_field :file, class: "btn" %>
        </span>
      </label>
    </div>
    <div class="input-group-append">
      <%= form.submit "Отправить", class: "btn btn-primary", id: 'chat-btn' %>
    </div>
  </div>

<% end %>

app/views/messages/_message.html.erb
<!-- Отображение сообщения только при наличии в нем текста или прикрепленного файла -->
<% if message.content? || message.file? %> 
    <!-- Разделение сообщений на сообщения от текущего пользователя или от кого-то другого -->
    <div class="message mb-2 <%= 'me' if message.user == current_user %><%= 'theirs' if message.user != current_user %>">
        <div class="content-container">
                <div class="author">
                    <!-- Точка, служащая для того, чтобы увидеть, находится ли пользователь в сети или нет -->
                    <span class='activity-status user-<%= message.user.id %>-status'>
                        •
                    </span>
                    <!-- Логин пользователя, написавшего сообщение-->
                    <%= message.user.login %>
                </div>
                <% if message.content? %>
                    <div class="content <%= 'marginfromfile' if (message.content? && message.file?) %>">
                        <%= message.content %>
                        <% if message.file? %>
                                <div>
                                    <% if message.file.content_type =~ /image/ %>
                                        <!-- <%= link_to(image_tag(message.file.url, alt: 'Image'), message.file.url) %> -->
                                        <%= link_to 'View Image', message.file.url, class: "viewfile" %> 
                                    <% else %>
                                        <%= link_to 'View File', message.file.url, class: "viewfile" %> 
                                    <% end %>
                                </div>
                        <% end %>
                    </div>
                <% elsif message.file?%> 
                    <div>
                        <% if message.file.content_type =~ /image/ %>
                            <%= link_to 'View Image', message.file.url, class: "viewfile" %> 
                        <% else %>
                            <%= link_to 'View File', message.file.url, class: "viewfile" %> 
                        <% end %>
                    </div>
                <% end %> 
        </div>
    </div>
<% end %> 

app/views/messages/_mine.html.erb
<div class="message mb-2 me">
    <div class="content-container">
        <div class="author">
            <span class='activity-status online user-<%= message.user.id %>-status'>
                •
            </span>
            <%= message.user.login %>
        </div>
        <div class="content">
            <%= message.content %>
            <% if message.file? %>
                <div class="fileview">
                    <% if message.file.content_type =~ /image/ %>
                        <%= link_to(image_tag(message.file.thumb.url, alt: 'Image'), message.file.url) %>
                    <% else %>
                        <%= link_to 'View File', message.file_url, class: "link-view" %> 
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message mb-2 theirs">
    <div class="content-container">
        <div class="author">
            <span class='activity-status online user-<%= message.user.id %>-status'>
                •
            </span>
            <%= message.user.login %>
        </div>
        <div class="content">
            <%= message.content %>
            <% if message.file? %>
                <div class="fileview">
                    <% if message.file.content_type =~ /image/ %>
                        <%= link_to(image_tag(message.file.thumb.url, alt: 'Image'), message.file.url) %>
                    <% else %>
                        <%= link_to 'View File', message.file_url, class: "link-view" %> 
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Chat</th>
      <th>File</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.user_id %></td>
        <td><%= message.chat_id %></td>
        <td><%= message.file %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form', message: @message %>
<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Chat:</strong>
  <%= @message.chat_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<!-- Окно регистрации. Пользователю предлагается зарегистрироваться, перейти к авторизации или вернуться назад -->
<%= form_with(model: user, local: true) do |form| %>
  <div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <div class="card-body">
            <% if user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                  <ul>
                    <% user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <h3 class="card-title mb-3">Зарегистрироваться</h3>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= form.label :login, "Логин" %>
                        <div class="input-group"> 
                          <%= form.text_field :login, class: 'form-control' %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= form.label :password, "Пароль" %>
                        <div class="input-group"> 
                          <%= form.password_field :password, class: 'form-control' %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= form.label :password_confirmation, "Подтвердите пароль" %>
                        <div class="input-group"> 
                          <%= form.password_field :password_confirmation, class: 'form-control' %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="actions">
              <p><%= form.submit "Зарегистрироваться", class: "btn btn-primary btn-block confirm-button" %></p>
            </div>
            <div class="row">
            <div class="col-sm-12">
              <%= link_to 'На главную страницу', root_url, class: 'btn btn-primary btn-block linkcolor'%>
            </div>
            </div>
        </div>
    </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_url %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= link_to 'Look at', user %></td>
        <td><%= link_to 'Change', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_url %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Change', edit_user_path(@user) %> |

<%= link_to 'Back', root_url %>